remote_theme: coursweb/jk-theme
title: Cours de révision
description: Un concept de cours de révision.
lang: fr-FR
markdown: GFM
chapters:
 - title: Cours-web
   url: https://cours-web.ch/
 - title: Eracom
   url: https://eracom.ch/

   # Footer content
# Content is split in three columns.   
footer_col_1: <ul class="contact-list">
  <li>Eracom, Lausanne</li>
  <li>2020–2021</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/coursweb/cours-revision">Lien Github</a></li></ul>